default_platform(:android)

platform :android do

  desc "Deploy to Internal Testing track"
  lane :internal do
    # Build release AAB
    sh("cd .. && flutter build appbundle --release")

    # Upload to Google Play internal track
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key: "fastlane/google-play-api.json",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "Promote Internal → Production"
  lane :deploy do
    upload_to_play_store(
      track: "internal",
      track_promote_to: "production",
      json_key: "fastlane/google-play-api.json",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

end
